# Default configuration file for ppvs

## Application settings
[DEFAULT]
    ups_ae_title = "UPSSCP"
    qr_ae_title = "QRSCP"
    # Our AE Title
    ae_title = "PPVS_SCP"
    # Our listen port
    #   This directory contains the QR service's managed SOP Instances
    import_staging_directory = "~/ppvs_import_staging"
    machine = "ProNova SC360 GR"
